server:
  port: 8080

spring:
  application:
    name: coffee-machine-adapters
  web:
    resources:
      add-mappings: true
      cache:
        period: PT0S
  datasource:
    url: jdbc:h2:mem:coffee-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.orm.jpa: info
