spring:
  main:
    web-application-type: servlet
    banner-mode: "off"
  datasource:
    url: jdbc:h2:mem:coffee-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  flyway:
    enabled: true

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.flywaydb: WARN
    com.zaxxer.hikari: WARN
    com.yonatankarp: INFO
